import Koa from "koa";
import bodyParser from "koa-bodyparser";
import qs from "koa-qs";
import { RegisterRoutes } from "./build-warehouse/routes";
import KoaRouter from "koa-router";
import { koaSwagger } from "koa2-swagger-ui";
import swagger from "../swagger.json"

export const app = new Koa();
qs(app);
app.use(bodyParser());

const koaRouter = new KoaRouter();

(RegisterRoutes as unknown as (koaRouter: KoaRouter) => void)(koaRouter);

// It's important that this come after the main routes are registered
app.use(async (context, next) => {
    try {
        await next();
    } catch (err: any) {
        context.status = err.status || 500;
        context.body = err.message || 'An error occurred during the request.';
    }
});

app.use(koaSwagger({
    routePrefix: '/docs',
    specPrefix: '/docs/spec',
    exposeSpec: true,
    swaggerOptions: {
        spec: swagger // This object is an import of the swagger.json generated by tsoa
    }
}))

app.use(koaRouter.routes()).use(koaRouter.allowedMethods());