version: "4.0"

services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-cache:/var/lib/nginx/cache

  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main
    volumes:
      - ./adapter:/source/adapter
      - ./mcmasteful-book-list.json:/source/mcmasteful-book-list.json

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db

  server1:
    image: geho16/orders-svc:latest

  server2:
    image: geho16/warehouse-svc:latest

  docs-svc:
    image: geho16/docs-svc:latest

  rabbitmq:
    image: rabbitmq:latest
