/* tslint:disable */
/* eslint-disable */
/**
 * TSOA
 * Build swagger-compliant REST APIs using TypeScript and Node
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrUpdateBookStockRequest
 */
export interface CreateOrUpdateBookStockRequest {
    /**
     * 
     * @type {number}
     * @memberof CreateOrUpdateBookStockRequest
     */
    numberOfBooks: number;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateBookStockRequest
     */
    bookId: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrUpdateBookStockRequest
     */
    shelf: string;
}

/**
 * Check if a given object implements the CreateOrUpdateBookStockRequest interface.
 */
export function instanceOfCreateOrUpdateBookStockRequest(value: object): value is CreateOrUpdateBookStockRequest {
    if (!('numberOfBooks' in value) || value['numberOfBooks'] === undefined) return false;
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    if (!('shelf' in value) || value['shelf'] === undefined) return false;
    return true;
}

export function CreateOrUpdateBookStockRequestFromJSON(json: any): CreateOrUpdateBookStockRequest {
    return CreateOrUpdateBookStockRequestFromJSONTyped(json, false);
}

export function CreateOrUpdateBookStockRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrUpdateBookStockRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'numberOfBooks': json['numberOfBooks'],
        'bookId': json['bookId'],
        'shelf': json['shelf'],
    };
}

export function CreateOrUpdateBookStockRequestToJSON(json: any): CreateOrUpdateBookStockRequest {
    return CreateOrUpdateBookStockRequestToJSONTyped(json, false);
}

export function CreateOrUpdateBookStockRequestToJSONTyped(value?: CreateOrUpdateBookStockRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'numberOfBooks': value['numberOfBooks'],
        'bookId': value['bookId'],
        'shelf': value['shelf'],
    };
}

