/* tslint:disable */
/* eslint-disable */
/**
 * TSOA
 * Build swagger-compliant REST APIs using TypeScript and Node
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FulfillOrderRequest
 */
export interface FulfillOrderRequest {
    /**
     * 
     * @type {number}
     * @memberof FulfillOrderRequest
     */
    quantity: number;
    /**
     * 
     * @type {string}
     * @memberof FulfillOrderRequest
     */
    bookId: string;
}

/**
 * Check if a given object implements the FulfillOrderRequest interface.
 */
export function instanceOfFulfillOrderRequest(value: object): value is FulfillOrderRequest {
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    if (!('bookId' in value) || value['bookId'] === undefined) return false;
    return true;
}

export function FulfillOrderRequestFromJSON(json: any): FulfillOrderRequest {
    return FulfillOrderRequestFromJSONTyped(json, false);
}

export function FulfillOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfillOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'quantity': json['quantity'],
        'bookId': json['bookId'],
    };
}

export function FulfillOrderRequestToJSON(json: any): FulfillOrderRequest {
    return FulfillOrderRequestToJSONTyped(json, false);
}

export function FulfillOrderRequestToJSONTyped(value?: FulfillOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'quantity': value['quantity'],
        'bookId': value['bookId'],
    };
}

