### Gets a list of all books
GET http://localhost:3000/books

### Gets a list of books ranging from $20 to $40
GET http://localhost:3000/books?filters[0][from]=20&filters[0][to]=40

### Get a book by ID
GET http://localhost:3000/books/{BookID}

### Delete a book by ID
DELETE http://localhost:3000/books/{BookID}

### Create a book
# POST http://localhost:3000/books

{
"name": "Test Book",
"author": "Test Author",
"description": "A test book",
"price": 99.99,
"image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b6/Gutenberg_Bible%2C_Lenox_Copy%2C_New_York_Public_Library%2C_2009._Pic_01.jpg/1280px-Gutenberg_Bible%2C_Lenox_Copy%2C_New_York_Public_Library%2C_2009._Pic_01.jpg"
}