name: Format, Lint, Type Checking
run-name: ${{ github.actor }} is formatting, linting and type checking.
on: [push]
jobs: 
    F-L-TC:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - run: echo "Running formatter ${{ github.event_name }}"
            - run: 
            - run: echo "Running linter ${{ github.event_name }}"
            - run: 
            - run: echo "Running type checking ${{ github.event_name }}"
            - run: 