name: Format, Lint, Type Checking
run-name: ${{ github.actor }} is formatting, linting and type checking.
on: [push, workflow_dispatch]
jobs:
    F-L-TC:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: 20
            - run: npm install
            
            - name: Run ESLint
              run: echo "Running linter ${{ github.event_name }}"
            - run: npm run lint
            
            - name: Run typechecking
              run: echo "Running type checking ${{ github.event_name }}"
            - run: npm run typecheck

            - run: echo "Running formatter ${{ github.event_name }}"
            - name: Run Prettier
              uses: creyD/prettier_action@v4.5
              with: 
                prettier_options: --write **/*.ts


    GenerateRoutes:
        runs-on: ubuntu-latest
        needs: F-L-TC
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: 20
            - run: npm install
            
            - name: Generate Routes
              run: echo "Generating routes ${{ github.event_name }}"
            - run: npm run generateroutes

            - name: Upload Routes
              uses: actions/upload-artifact@v4
              with:
                name: routes
                path: ./routes


    GenerateSDK:
        runs-on: ubuntu-latest
        needs: F-L-TC
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                node-version: 20
            - run: npm install
            
            - name: Generate SDK
              run: echo "Generating SDK ${{ github.event_name }}"
            - run: npm run generatesdk

            - name: Upload SDK
              uses: actions/upload-artifact@v4
              with:
                name: sdk
                path: ./client