name: Format, Lint, Type Checking
run-name: ${{ github.actor }} is formatting, linting and type checking.
on: [push, workflow_dispatch]
jobs:
    F-L-TC:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 20
            - run: npm install
            - run: echo "Running formatter ${{ github.event_name }}"
            - name: Run Prettier
              uses: creyD/prettier_action@v4.5
              with: 
                prettier_options: --write **/*.ts
            - run: echo $(ls -la)
            - run: echo "Running type checking ${{ github.event_name }}"
            - run: npm run typecheck
            - run: echo "Running linter ${{ github.event_name }}"
            - name: Run ESLint
              run: npm run lint